apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-metrics-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-metrics-api
  template:
    metadata:
      labels:
        app: student-metrics-api
    spec:
      containers:
      - name: student-metrics-api
        image: hashimasmara/student-metrics-api:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: student-metrics-api-service
spec:
  type: NodePort
  selector:
    app: student-metrics-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
