apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-metrics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-metrics-api
  template:
    metadata:
      labels:
        app: student-metrics-api
    spec:
  containers:
    - name: student-metrics-api
      image: student-metrics-api
      imagePullPolicy: Never
      ports:
        - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: student-metrics-api-service
spec:
  selector:
    app: student-metrics-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080

